var trigger = [
	"Hi, are you a chatbot?",
	"Hello, are you a virtual assistant?",
	"Hey, are you a bot?",
	"Are you currently on-duty?",
	"Are you available to assist me right now?",
	"Are you working at the moment?",
	"How can I log out of the system?",
	"Where can I find the logout option?",
	"What is the process to sign out?",
	"Is there more information available?",
	"Can I explore additional options?",
	"Are there more features to discover?",
	"How do I mark myself present?",
	"Where can I find the 'Present' button?",
	"What is the process to check myself in?",
	"How do I mark myself absent?",
	"Where can I find the 'Absent' button?",
	"What is the process to check myself out?",
	"How can I view my attendance record?",
	"Where can I find my attendance history?",
	"Is there a way to access my attendance data?",
	"How can I view my schedule?",
	"Where can I find my daily timetable?",
	"Is there a way to check my daily schedule?",
	"How do I generate an attendance report?",
	"Where can I find the 'Report' button?",
	"What is the process to obtain my attendance report?",
	"How can I add a new user?",
	"Where can I find the 'Add User' button?",
	"What is the process to register a new user?",
	"How do I remove a user?",
	"Where can I find the 'Remove User' button?",
	"What is the process to delete a user?",
	"How can I modify user information?",
	"Where can I update user details?",
	"What is the process to edit user data?",
	"How can I search for a specific user?",
	"Where can I find the user lookup feature?",
	"What is the process to find a particular user?",
	"How can I handle late arrivals?",
	"What is the process for late check-ins?",
	"Is there a way to handle late entries?",
	"How can I handle early departures?",
	"What is the process for early check-outs?",
	"Is there a way to handle early exits?",
	"How does the system handle public holidays?",
	"What is the process for marking holidays?",
	"Is there a way to indicate off days?",
	"How can I apply for an OD?",
	"Where can I find the OD application form?",
	"What is the process to request an OD?"
  ];
  
  var reply = [
	"Yes, I'm the chatbot. How can I assist you?",
	"I'm the virtual assistant. How may I help you?",
	"I'm here to help. What do you need?",
	"Yes, I'm currently on-duty and available to assist you.",
	"I'm working now. How can I assist you?",
	"Yes, I'm here and ready to help.",
	"To log out, click on the 'Logout' button in the top right corner.",
	"You can find the 'Logout' option in the top right corner to sign out.",
	"To log out, simply click on the 'Logout' button.",
	"To find more information, click on the 'Find More' button.",
	"You can explore more by clicking on the 'Find More' button.",
	"Clicking on the 'Find More' button will allow you to discover additional options.",
	"To mark yourself present, click on the 'Present' button on the home page.",
	"You can check yourself in by clicking on the 'Present' button.",
	"To mark yourself present, simply click on the 'Present' button.",
	"To mark yourself absent, click on the 'Absent' button on the home page.",
	"You can check yourself out by clicking on the 'Absent' button.",
	"To mark yourself absent, simply click on the 'Absent' button.",
	"To view your attendance record, go to the 'Attendance' section in the menu.",
	"You can find your attendance history in the 'Attendance' section of the system.",
	"To access your attendance data, navigate to the 'Attendance' section.",
	"To view your schedule, go to the 'Schedule' tab in the system.",
	"You can check your daily timetable under the 'Schedule' tab.",
	"To see your daily schedule, navigate to the 'Schedule' tab.",
	"To generate an attendance report, click on the 'Report' button and follow the instructions.",
	"You can obtain your attendance report by clicking on the 'Report' button.",
	"To generate your attendance report, simply click on the 'Report' button.",
	"To add a new user, go to the 'User Management' section and click on 'Add User'.",
	"You can register a new user by accessing the 'User Management' section and clicking on 'Add User'.",
	"To add a new user, navigate to the 'User Management' section and follow the 'Add User' process.",
	"To remove a user, go to the 'User Management' section and select the user to delete.",
	"You can delete a user by accessing the 'User Management' section and choosing the user to remove.",
	"To remove a user, navigate to the 'User Management' section and follow the process to delete the user.",
	"To modify user information, go to the 'User Management' section and edit the user details.",
	"You can update user information by accessing the 'User Management' section and modifying the user's details.",
	"To edit user data, navigate to the 'User Management' section and follow the process to modify the user information.",
	"To search for a specific user, use the search bar in the 'User Management' section.",
	"You can find a particular user by using the search feature in the 'User Management' section.",
	"To locate a specific user, navigate to the 'User Management' section and utilize the search functionality.",
	"To handle late arrivals, refer to the company's policy on late check-ins.",
	"The process for handling late check-ins is outlined in the company's guidelines.",
	"To manage late entries, please follow the procedures specified in the company's policy.",
	"To handle early departures, refer to the company's policy on early check-outs.",
	"The process for handling early check-outs is outlined in the company's guidelines.",
	"To manage early exits, please follow the procedures specified in the company's policy.",
	"The system automatically accounts for public holidays in the attendance record.",
	"Public holidays are automatically marked as non-working days in the attendance history.",
	"The system recognizes public holidays and excludes them from the attendance calculations.",
	"To apply for an OD, click on the 'OD Application' button and fill out the form.",
	"You can request an OD by accessing the 'OD Application' form and submitting the necessary information.",
	"To apply for an OD, navigate to the 'OD Application' section and follow the process to complete the form."
  ];
  
  function getChatbotReply(message) {
	for (var i = 0; i < trigger.length; i++) {
	  if (message.toLowerCase().includes(trigger[i].toLowerCase())) {
		return reply[i];
	  }
	}
	return "I'm sorry, I didn't understand that. Can you please rephrase your question?";
  }
  
  // Example usage:
  var userMessage = "Hi, are you a chatbot?";
  var chatbotResponse = getChatbotReply(userMessage);
  console.log(chatbotResponse);  // Outputs: "Yes, I'm the chatbot. How can I assist you?"
  